jwt:
    tile: 1000
    secret: hello-world no hello
posco:
    name: 3기 end
    count: 20
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: '{cipher}5033bd5777a2703e05f5a2c4407908748f35ccca3115a237db222198bc390302'
